// <auto-generated />
namespace MoneyApp.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class addBalance_toUser : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(addBalance_toUser));
        
        string IMigrationMetadata.Id
        {
            get { return "201806051721313_addBalance_toUser"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
